redis:
  image: redis
  container_name: cache
  expose:
    - 6379
app:
  image: yusufameri/cah:0.1.0
  links:
    - redis
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=5000
  ports:
    - "80:5000"
